### PR TITLE
Fixed the full request #90 that was rolled back. 

### PR DESCRIPTION
**Pull request by kdh92417**
# Description

- Adding the Parameter `misfire_grace_time` with a value of 120 to the `get_exporter_contents` scheduler job

### CODE REVIEW

**Comment by kdh92417** [comment]
Hi. @ralfyang 
I Modify the docker-compose.yml and committed it again. 
Please check it again.

**Comment by ralfyang** [comment]
Thanks @kdh92417 let me check now :)

**Comment by ralfyang** [comment]
It was worked! :) but we have diffrent issue as below.
image

The subpage detail is not working. Please check this issue out :)  @kdh92417 

Thanks.

**Comment by ralfyang** [comment]
Now, we have a lot of updates. due to the code conflict issue, this PR will be close without Merge.  @kdh92417 
Please open a new PR after the source code update. Thanks :)

**Pull request closed without merging**
