### PR TITLE
[Issue NexClipper#68] - Add shortcut information for recognize the contents existed or not on the list

### PR DESCRIPTION
**Pull request by Joylish**
## Overview
image

## Something to discuss
- [x] I don't know where to put the new mark in the header. So I commented out this part.
- [x] It was ambiguous to divide the criteria because each exporters has differnt types of contents.
This issue will be resolved after talking with @kdh92417

### CODE REVIEW

**Comment by ralfyang** [comment]
Please remove the `E` character. it's no need anymore :)
Thanks @Joylish

**Comment by Joylish** [comment]
Thanks for the comment of @ralfyang 

### Edited to reflect your comments
image

**Comment by ralfyang** [comment]
Thanks @Joylish ! I just check this out in my dev env. :)

**Comment by ralfyang** [comment]
when I test this commit in my dev. env. it's not working with the landing page screen as below
image

Sub-page working normally as below
image

**Comment by ralfyang** [comment]
I just attached screen capture for check the latency issue
image

**Comment by Joylish** [comment]
> I just attached screen capture for check the latency issue
> image

Thanks to comment, @ralfyang 

I think the latency problem is related to getting data from the api server and forwarding it.

To make the contents shortcut of the exporter this time, when the server gives each exporter information, contents information is added to the existing information.

Let's talk him about the delay problem. @kdh92417

**Comment by Joylish** [comment]
> when I test this commit in my dev. env. it's not working with the landing page screen as below
> image
> 
> Sub-page working normally as below
> image
> 
> Please check this issue out. Thanks :) @Joylish

thx comment to @ralfyang 

Please check after running server of python~~!!ㅎㅎ

**Comment by Joylish** [comment]
Dear @ralfyang ,
Now solve the problem you suggested🤣
check plz~~

### After edited in mobile view

**Comment by ralfyang** [comment]
@Joylish Thank you! let me check and merge this! :)

**Comment by ralfyang** [comment]
When I checked this commit for test, the page is noting show up as below capture.

image

**Comment by Joylish** [comment]
> When I checked this commit for test, the page is noting show up as below capture.
> 
> image

Did you run the django server? I think you didn't run server

**Comment by ralfyang** [comment]
Now, we have a lot of updates. due to the code conflict issue, this PR will be close without Merge.  @Joylish 
Please open a new PR after the source code update. Thanks :)

**Pull request closed without merging**
