### PR TITLE
[Issue #68] - Add function get_exporter_contents

### PR DESCRIPTION
**Pull request by kdh92417**
# Description
* Create a function that processes content data of exporters to send to clients
* schedule content data to be cached periodically.

# Details
Add function get_exporter_contents() 
Add a scheduler job for content data caching of exporters.
Add caching settings for file caching from settings

* Check if exporters' Iac, alert rule and grafana dashboard exits
* Send contents list created from backend to frontend
* Complete testing after communicating with the @Joylish 

# Feedback
* Fixed function name : get_exp_contents -> get_exporter_contents

Thank you for the feedback from @bart2001, @BaeJi77

### CODE REVIEW

**Comment by ralfyang** [comment]
we have some issue about this commit as below in the mobile view.
image

And, page rendering is little bit slow. so may the clock icon needed it. @Joylish 

Plese check this issue out :) 

Thnak you!

**Comment by kdh92417** [comment]
I'll check and revise it after discussing it with @Joylish

**Comment by ralfyang** [comment]
Hi @kdh92417  Your code has some slow response as below. Please check this issue out. Thanks :)
image

**Comment by ralfyang** [comment]
@kdh92417 you can test with this docker image - `nexclipper/exporterhub-api:release-api0.3.4-p90`
Thanks :)

**Comment by kdh92417** [comment]
Okay, I'll check the test server once again and improve the performance by creating an API that cashes the contents lists data.
Thanks :)

**Comment by kdh92417** [comment]
While working on caching, I have a question about the caching server.

- The api container fetches data from the caching server and the scheduler container tries to make the caching server scheduleable periodically.
- At this time, I want to add a container that runs the cache server to run the service. I'm curious what you think. @ralfyang

**Comment by bart2001** [comment]
> While working on caching, I have a question about the caching server.
> 
> * The api container fetches data from the caching server and the scheduler container tries to make the caching server scheduleable periodically.
> * At this time, I want to add a container that runs the cache server to run the service. I'm curious what you think. @ralfyang

how about using [mariabDB as Database caching](https://docs.djangoproject.com/en/3.2/topics/cache/#database-caching)?

**Comment by kdh92417** [comment]
Hi @ralfyang 
I modified the code to cache the contents data of the exporters every 5 minutes, so please check it once.

**Comment by ralfyang** [comment]
Okay! Thanks let me check :) @kdh92417

**Comment by ralfyang** [comment]
The page has something wrong as below.. please check this issue out @kdh92417.

image

**Comment by kdh92417** [comment]
I revised the Scheduler and ExporterView code and commited it again.
I'm sorry, but please check it again @ralfyang.

**Comment by ralfyang** [comment]
Thanks @kdh92417 :)
Let me check and I'll let you know the result. :)

**Comment by ralfyang** [comment]
I just checked this code working normally! Thanks :) @k

**Pull request merged**
